app = "app"
primary_region = "fra"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "1s"
  interval = "15s"
  method = "GET"
  path = "/"
  timeout = "2s"
